
spring:
  datasource:
    password: engenharia
    url: jdbc:mysql://localhost:3306/ger_veterinarios
    username: engenharia
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
  
  mvc:
    hiddenmethod:
      filter:
        enabled: true
